### ISSUE TITLE
How to solve the label problem？

### ISSUE THREAD

**Issue by qianyongsheng** [TianzhongSong/C3D-keras#1]
Hi TianzhongSong:
     Can you tell me how to make train_list.txt and test_list.txt ?You are handmade. Not necessarily the best recognition rate for every 16 entries
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01 1 0
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01 17 0
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01 33 0
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01 49 0
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01 65 0
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01 81 0
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01 97 0

your sincerely
Yongsheng Qian

**Comment by TianzhongSong** [comment]
@qianyongsheng use [make_label_txt](https://github.com/TianzhongSong/C3D-keras/blob/master/make_label_txt.py) and change the param clip_length.
