### ISSUE TITLE
local variable 'test_data' referenced before assignment

### ISSUE THREAD

**Issue by mrojasabregu** [TianzhongSong/C3D-keras#4]
Hi, 

I tried to run your code but it shown the following error in generator_val_batch 
[https://github.com/TianzhongSong/C3D-keras/blob/master/train_c3d.py#L138](
https://github.com/TianzhongSong/C3D-keras/blob/master/train_c3d.py#L138)

`test_data = np.transpose(test_data, (0, 2, 3, 1, 4)) `

UnboundLocalError: local variable 'test_data' referenced before assignment.
Do you have any idea?

**Comment by TianzhongSong** [comment]
@mrojasabregu  Oh, this is a code bug, and I have fixed it. 
 https://github.com/TianzhongSong/C3D-keras/blob/master/train_c3d.py#L138

**Comment by mrojasabregu** [comment]
Great! 
thanks
